# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35de568084cbafcfc5e61bbbd8c3f1b286eec485389dfc07d4a1bc4af336a920f3514ec11ee45c954feae17b1905db952105d1d58d22fdc72e6af68ee880790c

test:
  secret_key_base: a512931a4a7651a287490a8ce7d86e747353b404583b50e321815e16930015d504675f7a235517ee01fb0637580fe1b2adeda79c2bdfff87763bdf7d64a786e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
